<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5494877209995217"';
echo 'crossorigin="anonymous"></script>';
echo '<meta property="og:title" content="Motive.ml">';
echo '<meta property="og:type" content="website">';
echo '<meta property="og:url" content="http://motive.ml">';
echo '<meta property="og:image" content="https://motive.ml/favicon.png">';
echo '<meta property="og:description" content="Daily Inspirational Quotes">';
echo '<meta name="theme-color" content="#1c1c1c">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width">';
echo '<link rel="icon" type="image/x-icon" href="https://motive.ml/favicon.png">';
echo '<title>Motivational Quotes</title>';
echo '<link href="style.css" rel="stylesheet" type="text/css" />';
echo '</head>';
echo '<body>';
echo '<center>';
echo '<img src="https://motive.ml/logo_main.png" alt="logo" width = "200" height = "200">';
echo '<h1 style = "color: white;" class = "f2 , sp1">';
echo 'Daily Motivational Quotes';
echo '</h1>';
echo '<p class = "sp1 , f2" style = "color:white" id = "date"></p>';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h1 style = "color: white;" class = "f2 , sp1">';
echo 'Daily Quote:';
echo '</h1>';
echo '';
echo '<img class = "round" src="https://motive.ml/quote.png" alt="quote" width = "550" height = "300">';
echo '';
echo '<h1>                                                </h1>';
echo '';
echo '<a class = "f1 , sp1 , round" href="https://motive.ml/quote.png" download>Download Quote</a>';
echo '';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h2 style = "color: white;" class = "f2 , sp1">';
echo 'Support Us';
echo '</h2>';
echo '<a href="https://patreon.com/motivequotes" target="_blank" class="f1 , round , sp1">Become a Patron!</a>';
echo '<a href="https://www.youtube.com/channel/UClIvMfyQai-6Yt1AyUaekYA/" target="_blank" class="f1 , round , sp1">Subcribe to Our Youtube Channel</a>';
echo '';
echo '<a href="https://discord.gg/6MzBTTRVc8" target="_blank" class="f1 , round , sp1">Join our Discord Server</a>';
echo '';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h2 class = "f2 , sp1" style = "color: white;">About Us</h2>            <a href="https://motive.ml/aboutus.html" target="_blank" class="f1 , round , sp1">About</a>';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h2 class = "f2 , sp1" style = "color: white;">Download Our Android App</h2>';
echo '';
echo '<a class = "sp1 , f2 , round" href="https://motive.ml/motive.apk" target="_blank">Download</a>';
echo '<h2 style = "color: white;">________________________</h2>';
echo '';
echo '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5494877209995217"';
echo 'crossorigin="anonymous"></script>';
echo '<!-- ad_bottom -->';
echo '<ins class="adsbygoogle"';
echo 'style="display:block"';
echo 'data-ad-client="ca-pub-5494877209995217"';
echo 'data-ad-slot="3104327838"';
echo 'data-ad-format="auto"';
echo 'data-full-width-responsive="true"></ins>';
echo '<script>';
echo '(adsbygoogle = window.adsbygoogle || []).push({});';
echo '</script>';

echo '<script type="text/javascript" src="https://cookieconsent.popupsmart.com/src/js/popper.js"></script><script> window.start.init({Palette:"palette6",Theme:"classic",Message:"By using this website, you allow us to use cookies to give you the best experience on our site! ",LinkText:"Learn More",Time:"2",Mode:"banner bottom",})</script>';
echo '';
echo '</center>';
echo '<script src="script.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>
