<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta property="og:title" content="Motive.ml">';
echo '<meta property="og:type" content="website">';
echo '<meta property="og:url" content="http://motive.ml">';
echo '<meta property="og:image" content="https://motive.ml/favicon.png">';
echo '<meta property="og:description" content="Daily Inspirational Quotes">';
echo '<meta name="theme-color" content="#1c1c1c">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width">';
echo '<link rel="icon" type="image/x-icon" href="https://motive.ml/favicon.png">';
echo '<title>Motivational Quotes</title>';
echo '<link href="style.css" rel="stylesheet" type="text/css" />';
echo '</head>';
echo '<body>';
echo '<center>';
echo '<img src="https://motive.ml/logo_main.png" alt="logo" width = "200" height = "200">';
echo '<h1 style = "color: white;" class = "f2 , sp1">';
echo 'Daily Motivational Quotes';
echo '</h1>';
echo '<p class = "f2"><span id="datetime" class = "f2 , sp1" style = "color:white;">';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h2 style = "color: white;" class = "f2 , sp1">';
echo 'Website Starts In...';
echo '</h2>';
echo '<h1 class = "f2 , sp1" style = "color:white"  id="timer"></h1>';
echo '<h2 style = "color: white;">________________________</h2>';
echo '<h1 style = "color: white;" class = "f2 , sp1">';
echo 'Support Us!';
echo '</h1>';
echo '<a href="https://patreon.com/motivequotes" target="_blank" class="f1 , round">Become a Patron!</a>';
echo '<a href="https://www.youtube.com/channel/UClIvMfyQai-6Yt1AyUaekYA/" target="_blank" class="f1 , round">Subcribe to Our Youtube Channel</a>';
echo '</center>';
echo '<script src="script.js"></script>';
echo '</body>';
echo '</html>';
echo '';
?>